/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.gui;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jazbel Gutierrez
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }
    
    public static boolean comprobPassword=false;
    public static boolean comprobName=false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUser = new javax.swing.JTextField();
        pswUser = new javax.swing.JPasswordField();
        btnLoging = new javax.swing.JButton();
        lblPass = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        pswUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswUserActionPerformed(evt);
            }
        });

        btnLoging.setText("Iniciar Sesión");
        btnLoging.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogingActionPerformed(evt);
            }
        });

        lblPass.setText("Password");

        lblUser.setText("User");

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitle.setText("Sistema de Paga de Salarios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUser)
                    .addComponent(lblPass))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pswUser, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(txtUser))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLoging)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(103, 103, 103))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitle)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUser))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pswUser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPass))
                .addGap(39, 39, 39)
                .addComponent(btnLoging)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed

    }//GEN-LAST:event_txtUserActionPerformed

    private void btnLogingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogingActionPerformed
        this.validateUser();
        this.validatePass();
        AddInfo addInfo = new AddInfo();
        if(comprobPassword==true && comprobName==true){
            addInfo.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"Ingreso de datos erróneos.Por favor, inténtelo de nuevo","Error...",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnLogingActionPerformed

    private void pswUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswUserActionPerformed

    }//GEN-LAST:event_pswUserActionPerformed

    public void validateUser(){
        String[] user;
        String[] text;
        String employeeName="";
        boolean flag=true;
        char userName[] = txtUser.getText().toUpperCase().toCharArray();
        try{
            while(comprobName==false){
                employeeName=txtUser.getText();
                BufferedReader br = new BufferedReader (new FileReader ("Users.csv"));
                String contain=br.readLine();
                text=contain.split(";");
                comprobName = text[0].equals(employeeName);
            }
        }catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(int i=0;i<txtUser.getText().length();i++){
            userName[i]=txtUser.getText().charAt(i);
            if(userName[i]==0||userName[i]==1||userName[i]==2||userName[i]==3||userName[i]==4
                   ||userName[i]==5||userName[i]==6||userName[i]==7||userName[i]==8||userName[i]==9
                   ||userName[i]=='°'||userName[i]=='|'||userName[i]=='¬'||userName[i]=='!'||userName[i]=='"'
                   ||userName[i]=='#'||userName[i]=='$'||userName[i]=='%'||userName[i]=='&'||userName[i]=='/'
                   ||userName[i]=='('||userName[i]==')'||userName[i]=='='||userName[i]=='?'||userName[i]=='\''
                   ||userName[i]=='\\'||userName[i]=='¡'||userName[i]=='¿'||userName[i]=='*'||userName[i]=='+'
                   ||userName[i]=='¨'||userName[i]=='´'||userName[i]=='['||userName[i]=='{'||userName[i]=='^'
                   ||userName[i]==']'||userName[i]=='}'||userName[i]=='`'||userName[i]==';'||userName[i]==','
                   ||userName[i]==':'||userName[i]=='.'||userName[i]=='_'||userName[i]=='-'){
                flag=false;
            }else{
                flag=true;
            }
        }
        if(flag==false){
            JOptionPane.showMessageDialog(null,"Verifique su nombre de usuario","Advertencia",JOptionPane.INFORMATION_MESSAGE);
            comprobName=false;
        }else{
            if(employeeName.equals(txtUser.getText())){
                comprobName=true;
            }
        }
    }
    
    public void validatePass(){    
        String userPassword;
        String password;
        String[] text;
        
        try{
            
            while(comprobPassword==false){
                userPassword=pswUser.getText();
                BufferedReader br = new BufferedReader (new FileReader ("Users.csv"));
                String accessPassword=br.readLine();
                text=accessPassword.split(";");
                comprobPassword = text[1].equals(userPassword);
                System.out.println(text[1]);
            }
        }catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoging;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPasswordField pswUser;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
